url: "https://ssayebee.github.io"
collections:
  wiki:
    output: true
# Highlighter
highlighter: rouge
# Markdown
markdown: kramdown
# Comments
comments:
  provider: disqus
disqus:
  shortname: ssayebee
# Google Analytics
google_analyics: UA-175521892-1
